### ISSUE TITLE
Hi，这个可以采集公众号的评论内容吗

### ISSUE THREAD

**Issue by CuiYongen** [shinanL/wechatspider#1]
我查一些资料，好像最近微信公众号没办法按照原来的方法获取到 url 了，这个是可以正常使用的吗

**Comment by shinanL** [comment]
这个是利用自动化工具，在移动端模拟正常用户的浏览、点击等对服务器的请求操作，可以正常使用。



---原始邮件---
发件人: "CuiYongen"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 中午1:33
收件人: "shinanL/wechatspider"<wechatspider@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [shinanL/wechatspider] Hi，这个可以采集公众号的评论内容吗 (#1)




 
我查一些资料，好像最近微信公众号没办法按照原来的方法获取到 url 了，这个是可以正常使用的吗

**Comment by CuiYongen** [comment]
> 这个是利用自动化工具，在移动端模拟正常用户的浏览、点击等对服务器的请求操作，可以正常使用。
> […](#)
> ---原始邮件--- 发件人: "CuiYongen"<notifications@github.com&gt; 发送时间: 2020年5月28日(周四) 中午1:33 收件人: "shinanL/wechatspider"<wechatspider@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [shinanL/wechatspider] Hi，这个可以采集公众号的评论内容吗 (#1) 我查一些资料，好像最近微信公众号没办法按照原来的方法获取到 url 了，这个是可以正常使用的吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我看这是个 python 脚本，请问如何运行呢？
是需要用电脑连接手机，然后运行脚本吗？可以简单做个说明吗~

**Comment by shinanL** [comment]
需要手机通过USB连接电脑，下周出个详细的教程。



---原始邮件---
发件人: "CuiYongen"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 下午3:59
收件人: "shinanL/wechatspider"<wechatspider@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"meihaoxinqing"<liushinan@bupt.edu.cn&gt;;
主题: Re: [shinanL/wechatspider] Hi，这个可以采集公众号的评论内容吗 (#1)




  
这个是利用自动化工具，在移动端模拟正常用户的浏览、点击等对服务器的请求操作，可以正常使用。
 …
 ---原始邮件--- 发件人: "CuiYongen"<notifications@github.com&gt; 发送时间: 2020年5月28日(周四) 中午1:33 收件人: "shinanL/wechatspider"<wechatspider@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [shinanL/wechatspider] Hi，这个可以采集公众号的评论内容吗 (#1) 我查一些资料，好像最近微信公众号没办法按照原来的方法获取到 url 了，这个是可以正常使用的吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我看这是个 python 脚本，请问如何运行呢？
 是需要用电脑连接手机，然后运行脚本吗？可以简单做个说明吗~

**Comment by CuiYongen** [comment]
> 需要手机通过USB连接电脑，下周出个详细的教程。
> […](#)
> ---原始邮件--- 发件人: "CuiYongen"<notifications@github.com&gt; 发送时间: 2020年5月28日(周四) 下午3:59 收件人: "shinanL/wechatspider"<wechatspider@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"meihaoxinqing"<liushinan@bupt.edu.cn&gt;; 主题: Re: [shinanL/wechatspider] Hi，这个可以采集公众号的评论内容吗 (#1) 这个是利用自动化工具，在移动端模拟正常用户的浏览、点击等对服务器的请求操作，可以正常使用。 … ---原始邮件--- 发件人: "CuiYongen"<notifications@github.com&gt; 发送时间: 2020年5月28日(周四) 中午1:33 收件人: "shinanL/wechatspider"<wechatspider@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [shinanL/wechatspider] Hi，这个可以采集公众号的评论内容吗 (#1) 我查一些资料，好像最近微信公众号没办法按照原来的方法获取到 url 了，这个是可以正常使用的吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 我看这是个 python 脚本，请问如何运行呢？ 是需要用电脑连接手机，然后运行脚本吗？可以简单做个说明吗~ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，感谢！
